#!/usr/bin/php
<?php
require __DIR__ . '/vendor/autoload.php';

use RCTPHP\DatDataPrinter;

if ($argc < 2)
{
    echo "No filename specified!\n";
    exit(1);
}

$filename = $argv[1] ?? '';

$printer = new DatDataPrinter($filename);
$printer->printData();
