#!/usr/bin/php
<?php
require __DIR__ . '/../vendor/autoload.php';

use RCTPHP\Locomotion\Object\LocomotionDataPrinter;
use RCTPHP\RCT2\Object\RCT2DataPrinter;
use RCTPHP\Sawyer\Object\DatDataPrinter;

if ($argc < 2)
{
    echo "No filename specified!\n";
    exit(1);
}

$isLocomotion = !empty($argv[2]) ? (bool)(int)$argv[2] : false;
$class = $isLocomotion ? LocomotionDataPrinter::class : RCT2DataPrinter::class;

$filename = $argv[1] ?? '';

$printer = new $class($filename);
$printer->printData();
