#!/usr/bin/php
<?php
require __DIR__ . '/../vendor/autoload.php';

use RCTPHP\DatDataPrinter;

if ($argc < 2)
{
    echo "No filename specified!\n";
    exit(1);
}

$isLocomotion = !empty($argv[2]) ? (bool)(int)$argv[2] : false;

$filename = $argv[1] ?? '';

$printer = new DatDataPrinter($filename, $isLocomotion);
$printer->printData();
