#!/usr/bin/php
<?php

use RCTPHP\Util;

require __DIR__ . '/../vendor/autoload.php';

const ENCODED_ARRAY = [0x00, 0x47, 0xFF, 0x6F, 0x05, 0x64, 0x20, 0x6A, 0x6F, 0x62,0x21];
const DECODED_STRING = 'Good job!';

$encodedString = '';
foreach (ENCODED_ARRAY as $char)
{
    $encodedString .= chr($char);
}

//for ($i = 0; $i < strlen($srcString); $i++)
//{
//    Util::printLn(ord($srcString[$i]));
//}

$decodedRle = (new \RCTPHP\Sawyer\RLE\RLEString($encodedString))->decode();

Util::printLn('Decoding test:');
Util::printLn('--------------');
Util::printLn('Expected: ' . DECODED_STRING);
Util::printLn('Actual:   ' . $decodedRle);
Util::printLn((DECODED_STRING === $decodedRle) ? 'Success!' : 'Fail!');
Util::printLn('');


$encodedRLEObj = (new \RCTPHP\Sawyer\RLE\NonRLEString(DECODED_STRING))->encode();
$encodedRLE = $encodedRLEObj->getRaw();
Util::printLn('Encoding test:');
Util::printLn('--------------');
Util::printLn('Expected: ' . bin2hex($encodedString));
Util::printLn('Actual:   ' . bin2hex($encodedRLE));
Util::printLn(($encodedString === $encodedRLE) ? 'Success!' : 'Fail!');
